// FIX: Removed self-import of 'Screen' which was causing a declaration conflict.

export enum Screen {
  Onboarding,
  Welcome,
  Chat,
  Journal,
  Breathing,
  Resources,
}

export interface ChatMessage {
  id: number;
  text: string;
  sender: 'user' | 'ai';
}

export interface UserProfile {
  name: string;
  gender: string;
  dob: string;
}

// A new interface to structure saved chat conversations
export interface ChatSession {
  id: number; // Unique ID, can be a timestamp
  title: string; // AI-generated summary
  date: string; // ISO string date
  messages: ChatMessage[];
}

export interface JournalEntry {
  id: number;
  title: string;
  text: string;
  date: string; // ISO string date
}

// A comprehensive list of world languages, sorted alphabetically by name
export const LANGUAGES = [
  { code: 'af', name: 'Afrikaans', nativeName: 'Afrikaans' },
  { code: 'sq', name: 'Albanian', nativeName: 'Shqip' },
  { code: 'am', name: 'Amharic', nativeName: 'አማርኛ' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية' },
  { code: 'hy', name: 'Armenian', nativeName: 'Հայերեն' },
  { code: 'az', name: 'Azerbaijani', nativeName: 'azərbaycan dili' },
  { code: 'eu', name: 'Basque', nativeName: 'euskara' },
  { code: 'be', name: 'Belarusian', nativeName: 'беларуская мова' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'bs', name: 'Bosnian', nativeName: 'bosanski jezik' },
  { code: 'bg', name: 'Bulgarian', nativeName: 'български език' },
  { code: 'ca', name: 'Catalan', nativeName: 'català' },
  { code: 'ceb', name: 'Cebuano', nativeName: 'Cebuano' },
  { code: 'ny', name: 'Chichewa', nativeName: 'chiChewa' },
  { code: 'zh-CN', name: 'Chinese (Simplified)', nativeName: '简体中文' },
  { code: 'zh-TW', name: 'Chinese (Traditional)', nativeName: '繁體中文' },
  { code: 'co', name: 'Corsican', nativeName: 'corsu' },
  { code: 'hr', name: 'Croatian', nativeName: 'hrvatski jezik' },
  { code: 'cs', name: 'Czech', nativeName: 'čeština' },
  { code: 'da', name: 'Danish', nativeName: 'dansk' },
  { code: 'nl', name: 'Dutch', nativeName: 'Nederlands' },
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'eo', name: 'Esperanto', nativeName: 'Esperanto' },
  { code: 'et', name: 'Estonian', nativeName: 'eesti' },
  { code: 'tl', name: 'Filipino', nativeName: 'Filipino' },
  { code: 'fi', name: 'Finnish', nativeName: 'suomi' },
  { code: 'fr', name: 'French', nativeName: 'français' },
  { code: 'fy', name: 'Frisian', nativeName: 'Frysk' },
  { code: 'gl', name: 'Galician', nativeName: 'galego' },
  { code: 'ka', name: 'Georgian', nativeName: 'ქართული' },
  { code: 'de', name: 'German', nativeName: 'Deutsch' },
  { code: 'el', name: 'Greek', nativeName: 'Ελληνικά' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'ht', name: 'Haitian Creole', nativeName: 'Kreyòl ayisyen' },
  { code: 'ha', name: 'Hausa', nativeName: 'Hausa' },
  { code: 'haw', name: 'Hawaiian', nativeName: 'ʻŌlelo Hawaiʻi' },
  { code: 'iw', name: 'Hebrew', nativeName: 'עברית' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'hmn', name: 'Hmong', nativeName: 'Hmong' },
  { code: 'hu', name: 'Hungarian', nativeName: 'magyar' },
  { code: 'is', name: 'Icelandic', nativeName: 'Íslenska' },
  { code: 'ig', name: 'Igbo', nativeName: 'Asụsụ Igbo' },
  { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia' },
  { code: 'ga', name: 'Irish', nativeName: 'Gaeilge' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語' },
  { code: 'jw', name: 'Javanese', nativeName: 'basa Jawa' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'kk', name: 'Kazakh', nativeName: 'қазақ тілі' },
  { code: 'km', name: 'Khmer', nativeName: 'ພາສາខ្ែរ' },
  { code: 'ko', name: 'Korean', nativeName: '한국어' },
  { code: 'ku', name: 'Kurdish', nativeName: 'Kurdî' },
  { code: 'ky', name: 'Kyrgyz', nativeName: 'Кыргызча' },
  { code: 'lo', name: 'Lao', nativeName: 'ພາສາລາວ' },
  { code: 'la', name: 'Latin', nativeName: 'latine' },
  { code: 'lv', name: 'Latvian', nativeName: 'latviešu valoda' },
  { code: 'lt', name: 'Lithuanian', nativeName: 'lietuvių kalba' },
  { code: 'lb', name: 'Luxembourgish', nativeName: 'Lëtzebuergesch' },
  { code: 'mk', name: 'Macedonian', nativeName: 'македонски јазик' },
  { code: 'mg', name: 'Malagasy', nativeName: 'Malagasy' },
  { code: 'ms', name: 'Malay', nativeName: 'bahasa Melayu' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'mt', name: 'Maltese', nativeName: 'Malti' },
  { code: 'mi', name: 'Maori', nativeName: 'te reo Māori' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'mn', name: 'Mongolian', nativeName: 'Монгол' },
  { code: 'my', name: 'Myanmar (Burmese)', nativeName: 'ဗမာစာ' },
  { code: 'ne', name: 'Nepali', nativeName: 'नेपाली' },
  { code: 'no', name: 'Norwegian', nativeName: 'Norsk' },
  { code: 'ps', name: 'Pashto', nativeName: 'پښتو' },
  { code: 'fa', name: 'Persian', nativeName: 'فارسی' },
  { code: 'pl', name: 'Polish', nativeName: 'polski' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
  { code: 'ro', name: 'Romanian', nativeName: 'română' },
  { code: 'ru', name: 'Russian', nativeName: 'русский' },
  { code: 'sm', name: 'Samoan', nativeName: 'gagana faʻa Samoa' },
  { code: 'gd', name: 'Scots Gaelic', nativeName: 'Gàidhlig' },
  { code: 'sr', name: 'Serbian', nativeName: 'српски језик' },
  { code: 'st', name: 'Sesotho', nativeName: 'Sesotho' },
  { code: 'sn', name: 'Shona', nativeName: 'chiShona' },
  { code: 'sd', name: 'Sindhi', nativeName: 'सिन्धी' },
  { code: 'si', name: 'Sinhala', nativeName: 'සිංහල' },
  { code: 'sk', name: 'Slovak', nativeName: 'slovenčina' },
  { code: 'sl', name: 'Slovenian', nativeName: 'slovenščina' },
  { code: 'so', name: 'Somali', nativeName: 'Soomaaliga' },
  { code: 'es', name: 'Spanish', nativeName: 'español' },
  { code: 'su', name: 'Sundanese', nativeName: 'Basa Sunda' },
  { code: 'sw', name: 'Swahili', nativeName: 'Kiswahili' },
  { code: 'sv', name: 'Swedish', nativeName: 'svenska' },
  { code: 'tg', name: 'Tajik', nativeName: 'тоҷикӣ' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'th', name: 'Thai', nativeName: 'ไทย' },
  { code: 'tr', name: 'Turkish', nativeName: 'Türkçe' },
  { code: 'uk', name: 'Ukrainian', nativeName: 'українська' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو' },
  { code: 'uz', name: 'Uzbek', nativeName: 'Oʻzbek' },
  { code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt' },
  { code: 'cy', name: 'Welsh', nativeName: 'Cymraeg' },
  { code: 'xh', name: 'Xhosa', nativeName: 'isiXhosa' },
  { code: 'yi', name: 'Yiddish', nativeName: 'ייִדיש' },
  { code: 'yo', name: 'Yoruba', nativeName: 'Yorùbá' },
  { code: 'zu', name: 'Zulu', nativeName: 'isiZulu' },
].sort((a, b) => a.name.localeCompare(b.name));


// i18n translations
export const translations = {
  en: {
    // Onboarding
    welcomeToMannMitra: "Welcome to Mann Mitra 💙",
    letsGetToKnowYou: "Let's get to know you a bit. This stays on your device and helps personalize your experience.",
    whatShouldICallYou: "What should I call you?",
    yourName: "Your Name",
    gender: "Gender",
    selectYourGender: "Select your gender",
    male: "Male",
    female: "Female",
    other: "Other",
    preferNotToSay: "Prefer not to say",
    dateOfBirth: "Date of Birth",
    preferredLanguage: "Preferred Language",
    selectYourLanguage: "Select your language",
    pleaseFillAllFields: "Please fill in all fields to continue.",
    couldNotSaveDetails: "Could not save your details. Please ensure your browser supports local storage.",
    saveAndContinue: "Save & Continue",

    // Welcome
    yourMindsFriend: "Your Mind’s Friend — Confidential. Supportive. Non-judgmental.",
    startConversation: "Start Conversation →",
    
    // Chat
    profile: "Profile",
    history: "History",
    breathing: "Breathing",
    journal: "Journal",
    resources: "Resources",
    voice: "Voice",
    typeAMessage: "Type a message...",
    initialChatMessage: "Hey there! I'm Mann Mitra, your mind's friend. Thanks for stopping by. What's on your mind today? Feel free to share as much or as little as you'd like. 💙",
    listening: "Listening...",
    thinking: "Thinking...",
    yourProfile: "Your Profile",
    name: "Name",
    noProfileInfo: "No profile information found.",
    clearDataAndReset: "Clear Data & Reset App",
    confirmReset: "Click again to confirm",
    chatHistory: "Chat History",
    newChat: "+ New Chat",
    newChatTitle: "New Conversation",
    creating: "Creating...",
    clearAllHistory: "Clear All History",
    confirmClear: "Confirm Clear?",
    voiceAssistant: "Voice Assistant",
    enableVoiceAssistant: "Enable Voice Assistant",
    language: "Language",
    selectLanguage: "Select Language",
    english: "English",
    hindi: "Hindi",
    chooseAVoice: "Choose a Voice",
    femaleVoice: "Female Voice",
    maleVoice: "Male Voice",
    aQuickThought: "A Quick Thought",
    chatReflection: "Chat Reflection",
    generateTitlePrompt: `Read the following chat between a user and an AI wellness companion. Create a short, gentle title (5 words max) that captures the core feeling or topic. Examples: "Feeling Overwhelmed at Work," "Reflecting on Friendship," "A Moment of Sadness." Do not use quotation marks.\n\nConversation:\n`,
    voicePreview: "Hello, this is the selected voice.",
    voiceErrorGeneric: "Sorry, voice input failed. Please try again.",
    voiceErrorNoSpeech: "I didn't catch that. Please try speaking again.",
    voiceErrorNotAllowed: "Microphone access is needed for voice input.",
    
    // Journal
    yourSafeSpace: "Your Safe Space ✨",
    giveYourReflectionTitle: "Give your reflection a title...",
    writeDownYourThoughts: "Write down your thoughts, feelings, or anything on your mind. This is your private corner 💛",
    saveMyReflection: "Save My Reflection 📝",
    backToChat: "← Back to Chat",
    yourReflections: "Your Reflections ❤️",
    noJournalEntries: "You haven't written any journal entries yet.",
    savedReflectionsAppearHere: "Your saved reflections will appear here.",
    backToJournal: "← Back to Journal",
    backToReflections: "← Back to Reflections",
    deleteEntry: "Delete entry",
    confirmDeletion: "Confirm deletion",
    confirm: "Confirm?",
    greatJobJournaling: "Great job journaling ✨ Writing reduces stress by 30%.",
    reflectionOn: "Reflection on ",
    
    // Breathing
    takeADeepBreath: "Take a Deep Breath 🌿",
    breathingExerciseDescription: "Follow this simple box breathing exercise to relax, refocus, and recharge your mind.",
    startBreathing: "Start Breathing 🌬️",
    getReady: "Get Ready...",
    inhale: "Inhale…2…3…4 🌿",
    hold: "Hold…",
    exhale: "Exhale…2…3…4 🌿",
    pause: "Pause…",
    endSessionAndReturn: "End Session & Return",

    // Resources
    youAreNotAlone: "You’re Not Alone 💙",
    immediateDangerWarning: "If you are in immediate danger, please call your local emergency number.",
    helplineKiran: "KIRAN Mental Health Helpline",
    helplineKiranDesc: "24x7, a Government of India initiative.",
    helplineVandrevala: "Vandrevala Foundation Helpline",
    helplineVandrevalaDesc: "24x7, multilingual support.",
    helplineAasra: "AASRA (Suicide Prevention)",
    helplineAasraDesc: "24x7, confidential support for those in distress.",
    helplineIcall: "iCALL Psychosocial Helpline (TISS)",
    helplineIcallDesc: "Mon–Sat, 8am–10pm. Professional counselling.",
  },
  hi: {
    // Onboarding
    welcomeToMannMitra: "Mann Mitra 💙 में आपका स्वागत है",
    letsGetToKnowYou: "आइए हम आपको थोड़ा जानें। यह आपके डिवाइस पर रहता है और आपके अनुभव को व्यक्तिगत बनाने में मदद करता है।",
    whatShouldICallYou: "मैं आपको क्या कह कर बुलाऊं?",
    yourName: "आपका नाम",
    gender: "लिंग",
    selectYourGender: "अपना लिंग चुनें",
    male: "पुरुष",
    female: "महिला",
    other: "अन्य",
    preferNotToSay: "बताना नहीं चाहते",
    dateOfBirth: "जन्म की तारीख",
    preferredLanguage: "पसंदीदा भाषा",
    selectYourLanguage: "अपनी भाषा चुनें",
    pleaseFillAllFields: "कृपया जारी रखने के लिए सभी फ़ील्ड भरें।",
    couldNotSaveDetails: "आपका विवरण सहेजा नहीं जा सका। कृपया सुनिश्चित करें कि आपका ब्राउज़र स्थानीय भंडारण का समर्थन करता है।",
    saveAndContinue: "सहेजें और जारी रखें",
    
    // Welcome
    yourMindsFriend: "आपके मन का मित्र — गोपनीय। सहायक। गैर-निर्णयात्मक।",
    startConversation: "बातचीत शुरू करें →",

    // Chat
    profile: "प्रोफ़ाइल",
    history: "इतिहास",
    breathing: "साँस लेना",
    journal: "जर्नल",
    resources: "संसाधन",
    voice: "आवाज़",
    typeAMessage: "एक संदेश लिखें...",
    initialChatMessage: "नमस्ते! मैं मन मित्र हूँ, आपके मन का दोस्त। यहाँ आने के लिए धन्यवाद। आज आपके मन में क्या है? आप जितना चाहें उतना या कम साझा करने के लिए स्वतंत्र महसूस करें। 💙",
    listening: "सुन रहा हूँ...",
    thinking: "सोच रहा हूँ...",
    yourProfile: "आपकी प्रोफ़ाइल",
    name: "नाम",
    noProfileInfo: "कोई प्रोफ़ाइल जानकारी नहीं मिली।",
    clearDataAndReset: "डेटा साफ़ करें और ऐप रीसेट करें",
    confirmReset: "पुष्टि करने के लिए फिर से क्लिक करें",
    chatHistory: "चैट इतिहास",
    newChat: "+ नई चैट",
    newChatTitle: "नई बातचीत",
    creating: "बना रहा है...",
    clearAllHistory: "सारा इतिहास साफ़ करें",
    confirmClear: "क्या आप वाकई हटाना चाहते हैं?",
    voiceAssistant: "आवाज सहायक",
    enableVoiceAssistant: "आवाज सहायक सक्षम करें",
    language: "भाषा",
    selectLanguage: "भाषा चुनें",
    english: "English",
    hindi: "हिन्दी",
    chooseAVoice: "एक आवाज़ चुनें",
    femaleVoice: "महिला आवाज",
    maleVoice: "पुरुष आवाज",
    aQuickThought: "एक त्वरित विचार",
    chatReflection: "चैट चिंतन",
    generateTitlePrompt: `एक उपयोगकर्ता और एक एआई वेलनेस साथी के बीच निम्नलिखित चैट पढ़ें। एक छोटा, सौम्य शीर्षक (अधिकतम 5 शब्द) बनाएं जो मुख्य भावना या विषय को दर्शाता हो। उदाहरण: "काम पर अभिभूत महसूस करना," "दोस्ती पर चिंतन," "उदासी का एक पल।" उद्धरण चिह्नों का प्रयोग न करें।\n\nबातचीत:\n`,
    voicePreview: "नमस्ते, यह चुनी हुई आवाज़ है।",
    voiceErrorGeneric: "क्षमा करें, वॉयस इनपुट विफल रहा। कृपया पुनः प्रयास करें।",
    voiceErrorNoSpeech: "मैंने वह नहीं सुना। कृपया फिर से बोलने का प्रयास करें।",
    voiceErrorNotAllowed: "वॉयस इनपुट के लिए माइक्रोफ़ोन एक्सेस की आवश्यकता है।",

    // Journal
    yourSafeSpace: "आपकी सुरक्षित जगह ✨",
    giveYourReflectionTitle: "अपने चिंतन को एक शीर्षक दें...",
    writeDownYourThoughts: "अपने विचार, भावनाएँ, या मन में जो कुछ भी है, उसे लिखें। यह आपका निजी कोना है 💛",
    saveMyReflection: "मेरा चिंतन सहेजें 📝",
    backToChat: "← चैट पर वापस जाएं",
    yourReflections: "आपके चिंतन ❤️",
    noJournalEntries: "आपने अभी तक कोई जर्नल प्रविष्टि नहीं लिखी है।",
    savedReflectionsAppearHere: "आपके सहेजे गए चिंतन यहाँ दिखाई देंगे।",
    backToJournal: "← जर्नल पर वापस जाएं",
    backToReflections: "← चिंतन पर वापस जाएं",
    deleteEntry: "प्रविष्टि हटाएं",
    confirmDeletion: "हटाने की पुष्टि करें",
    confirm: "पुष्टि करें?",
    greatJobJournaling: "बहुत अच्छा जर्नलिंग ✨ लिखने से तनाव 30% कम होता है।",
    reflectionOn: "इस पर चिंतन ",

    // Breathing
    takeADeepBreath: "एक गहरी साँस लें 🌿",
    breathingExerciseDescription: "अपने मन को शांत करने, फिर से ध्यान केंद्रित करने और रिचार्ज करने के लिए इस सरल बॉक्स ब्रीदिंग व्यायाम का पालन करें।",
    startBreathing: "साँस लेना शुरू करें 🌬️",
    getReady: "तैयार हो जाओ...",
    inhale: "साँस अंदर लें…२…३…४ 🌿",
    hold: "रोकें…",
    exhale: "साँस बाहर छोड़ें…२…३…४ 🌿",
    pause: "विराम…",
    endSessionAndReturn: "सत्र समाप्त करें और लौटें",

    // Resources
    youAreNotAlone: "आप अकेले नहीं हैं 💙",
    immediateDangerWarning: "यदि आप तत्काल खतरे में हैं, तो कृपया अपने स्थानीय आपातकालीन नंबर पर कॉल करें।",
    helplineKiran: "किरण मानसिक स्वास्थ्य हेल्पलाइन",
    helplineKiranDesc: "24x7, भारत सरकार की एक पहल।",
    helplineVandrevala: "वंद्रेवाला फाउंडेशन हेल्पलाइन",
    helplineVandrevalaDesc: "24x7, बहुभाषी समर्थन।",
    helplineAasra: "आसरा (आत्महत्या रोकथाम)",
    helplineAasraDesc: "24x7, संकट में लोगों के लिए गोपनीय समर्थन।",
    helplineIcall: "iCALL साइकोसोशल हेल्पलाइन (TISS)",
    helplineIcallDesc: "सोम-शनि, सुबह 8 बजे से रात 10 बजे तक। पेशेवर परामर्श।",
  }
};

export type TranslationKey = keyof typeof translations.en;
export type Language = string;